@startuml
actor 用户
entity "ProfileActivity" as Activity
entity "Handler (主线程)" as Handler
entity "Glide" as Glide
entity "FileDownloader" as Downloader

用户 -> Activity : 打开界面
Activity -> Downloader : 启动下载线程
Downloader -> File : 下载文件
File -> Downloader : 文件下载完成
Downloader -> Activity : 下载完成通知
Activity -> Handler : 通知主线程加载图片
Handler -> Glide : 使用 Glide 加载图片
Glide -> Activity : 图片加载完成
Activity -> 用户 : 显示头像

@enduml
